In [21]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split

In [22]:
df=pd.read_csv("/content/drive/MyDrive/python/Dataset/travel_packages.csv")
df

,index,place,price,time,about_trip,emi
0,0,manali,"18,699",\n 6 NIGHTS\n ...,"\n\tAfter breakfast, drive to Delhi for your r...","1,149\n"
1,1,new delhi,"4,999",\n 2 NIGHTS\n ...,\n\tUpon arrival in Delhi head straight to Amr...,307\n
2,2,new delhi,"4,999",\n 2 NIGHTS\n ...,\n\tUpon arrival in Delhi drive straight to La...,307\n
3,3,jaipur,"6,100",\n 2 NIGHTS\n ...,\n\t\n\t\tUpon your arrival in Bharatpur from ...,375\n
4,4,jaipur,"6,100",\n 2 NIGHTS\n ...,"\n\tPost pick-up from Delhi, travel to Jaipur ...",375\n
...,...,...,...,...,...,...
1604,1604,bhutan winter Packages,"29,999",\n 5 NIGHTS\n ...,"\n\t\n\t\t\n\t\t\t\n\t\t\t\tAfter breakfast, s...","1,843\n"
1605,1605,sri lanka winter Packages,"18,799",\n 3 NIGHTS\n ...,\n\t\n\t\t\n\t\t\tMeet and assist on arrival a...,"1,155\n"
1606,1606,bhutan winter Packages,"22,500",\n 4 NIGHTS\n ...,"\n\t\n\t\t\n\t\t\t\n\t\t\t\tAfter breakfast, s...","1,383\n"
1607,1607,sri lanka winter Packages,"15,999",\n 3 NIGHTS\n ...,\n\t\n\t\t\n\t\t\tMeet and assist on arrival a...,983\n
1608,1608,hong kong winter Packages,"65,990",\n 5 NIGHTS\n ...,"\n\tOn your arrival in Hong Kong, get set to b...","4,055\n"

In [23]:
new_df=df.drop(['index','about_trip','emi'],axis='columns')
new_df

,place,price,time
0,manali,"18,699",\n 6 NIGHTS\n ...
1,new delhi,"4,999",\n 2 NIGHTS\n ...
2,new delhi,"4,999",\n 2 NIGHTS\n ...
3,jaipur,"6,100",\n 2 NIGHTS\n ...
4,jaipur,"6,100",\n 2 NIGHTS\n ...
...,...,...,...
1604,bhutan winter Packages,"29,999",\n 5 NIGHTS\n ...
1605,sri lanka winter Packages,"18,799",\n 3 NIGHTS\n ...
1606,bhutan winter Packages,"22,500",\n 4 NIGHTS\n ...
1607,sri lanka winter Packages,"15,999",\n 3 NIGHTS\n ...
1608,hong kong winter Packages,"65,990",\n 5 NIGHTS\n ...

In [24]:
new_df['time'].unique()

array(['\n                            6 NIGHTS\n                        ',
       '\n                            2 NIGHTS\n                        ',
       '\n                            5 NIGHTS\n                        ',
       '\n                            7 NIGHTS\n                        ',
       '\n                            4 NIGHTS\n                        ',
       '\n                            3 NIGHTS\n                        ',
       '\n                            8 NIGHTS\n                        ',
       '\n                            9 NIGHTS\n                        ',
       '\n                            1 NIGHT\n                        ',
       '\n                            10 NIGHTS\n                        ',
       '\n                            13 NIGHTS\n                        ',
       '\n                            15 NIGHTS\n                        ',
       '\n                            12 NIGHTS\n                        ',
       '\n                            17 NIGHTS\n                        ',
       '\n                            11 NIGHTS\n                        ',
       '\n                            16 NIGHTS\n                        ',
       '\n                            14 NIGHTS\n                        ',
       '\n                            19 NIGHTS\n                        '],
      dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le=LabelEncoder()

In [27]:
new_df['time']=le.fit_transform(new_df['time'])
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(class_mapping)

{'\n                            1 NIGHT\n                        ': 0, '\n                            10 NIGHTS\n                        ': 1, '\n                            11 NIGHTS\n                        ': 2, '\n                            12 NIGHTS\n                        ': 3, '\n                            13 NIGHTS\n                        ': 4, '\n                            14 NIGHTS\n                        ': 5, '\n                            15 NIGHTS\n                        ': 6, '\n                            16 NIGHTS\n                        ': 7, '\n                            17 NIGHTS\n                        ': 8, '\n                            19 NIGHTS\n                        ': 9, '\n                            2 NIGHTS\n                        ': 10, '\n                            3 NIGHTS\n                        ': 11, '\n                            4 NIGHTS\n                        ': 12, '\n                            5 NIGHTS\n                        ': 13, '\n                            6 NIGHTS\n                        ': 14, '\n                            7 NIGHTS\n                        ': 15, '\n                            8 NIGHTS\n                        ': 16, '\n                            9 NIGHTS\n                        ': 17}

In [28]:
new_df['price']=pd.Series(new_df['price']).str.replace(',','').astype(int)

In [29]:
new_df

                           place  price  time
0                         manali  18699    14
1                      new delhi   4999    10
2                      new delhi   4999    10
3                         jaipur   6100    10
4                         jaipur   6100    10
...                          ...    ...   ...
1604     bhutan winter  Packages  29999    13
1605  sri lanka winter  Packages  18799    11
1606     bhutan winter  Packages  22500    12
1607  sri lanka winter  Packages  15999    11
1608  hong kong winter  Packages  65990    13

[1609 rows x 3 columns]

In [30]:
new_df['place']=le.fit_transform(new_df['place'])
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(class_mapping)

{'aberdare': 0, 'abu dhabi': 1, 'agra': 2, 'alibag': 3, 'amman': 4, 'amritsar': 5, 'amsterdam': 6, 'andaman and nicobar islands': 7, 'andhra pradesh': 8, 'athens': 9, 'auckland': 10, 'australia': 11, 'austria': 12, 'bali': 13, 'bandipur': 14, 'banff': 15, 'bangkok': 16, 'barcelona': 17, 'belgium': 18, 'bengaluru': 19, 'bergen': 20, 'berlin': 21, 'bhutan': 22, 'bhutan winter  Packages': 23, 'bikaner': 24, 'bintan island': 25, 'brisbane': 26, 'brussels': 27, 'budapest': 28, 'cairns': 29, 'calgary': 30, 'cambodia': 31, 'canada': 32, 'cape town': 33, 'cappadocia': 34, 'chandigarh': 35, 'changla pass': 36, 'cherrapunji': 37, 'chiang mai': 38, 'chiang rai': 39, 'china': 40, 'chittorgarh': 41, 'christchurch': 42, 'cologne': 43, 'colombo': 44, 'coorg': 45, 'copenhagen': 46, 'corbett': 47, 'cordoba': 48, 'croatia': 49, 'czech republic': 50, 'dalhousie': 51, 'dead sea': 52, 'dharamshala': 53, 'dubai': 54, 'dublin': 55, 'dubrovnik': 56, 'egypt': 57, 'engelberg': 58, 'europe': 59, 'fiji': 60, 'florence': 61, 'france': 62, 'frankfurt': 63, 'gangtok': 64, 'ganpatipule': 65, 'geneva': 66, 'genting highland': 67, 'germany': 68, 'goa': 69, 'gold coast': 70, 'granada': 71, 'greece': 72, 'gulmarg': 73, 'guwahati': 74, 'hamburg': 75, 'hamilton island': 76, 'hanoi': 77, 'haridwar': 78, 'helsinki': 79, 'hong kong': 80, 'hong kong winter  Packages': 81, 'hua hin & cha am': 82, 'hungary': 83, 'iceland': 84, 'indonesia': 85, 'interlaken': 86, 'inverness': 87, 'ireland': 88, 'israel': 89, 'istanbul': 90, 'jaipur': 91, 'jaisalmer': 92, 'jammu': 93, 'jammu and kashmir': 94, 'japan': 95, 'jodhpur': 96, 'johannesburg': 97, 'jordan': 98, 'kalimpong': 99, 'kargil': 100, 'kasauli': 101, 'kathmandu': 102, 'kenya': 103, 'kerala': 104, 'kochi': 105, 'kodaikanal': 106, 'koh phangan': 107, 'koh samui': 108, 'krabi': 109, 'krakow': 110, 'kuala lumpur': 111, 'kufri': 112, 'lachung': 113, 'lake louise': 114, 'langkawi': 115, 'lansdowne': 116, 'las vegas': 117, 'latvia': 118, 'lithuania': 119, 'ljubljana': 120, 'lonavala': 121, 'london': 122, 'lugano': 123, 'macau': 124, 'madrid': 125, 'mahabalipuram': 126, 'malaga': 127, 'malaysia': 128, 'maldives': 129, 'manali': 130, 'mandawa': 131, 'mararikulam': 132, 'masai mara': 133, 'matheran': 134, 'mauritius': 135, 'meghalaya': 136, 'melbourne': 137, 'miami': 138, 'milan': 139, 'montreux': 140, 'mount abu': 141, 'mumbai': 142, 'munich': 143, 'munnar': 144, 'muscat': 145, 'mussoorie': 146, 'myanmar': 147, 'mykonos': 148, 'nainital': 149, 'nairobi': 150, 'naivasha': 151, 'nepal': 152, 'netherlands': 153, 'new delhi': 154, 'new south wales': 155, 'new york': 156, 'new zealand': 157, 'niagara falls': 158, 'north goa': 159, 'norway': 160, 'nubra': 161, 'oman': 162, 'orlando': 163, 'oslo': 164, 'padova': 165, 'pahalgam': 166, 'paris': 167, 'paro': 168, 'pattaya': 169, 'penang': 170, 'petra': 171, 'philadelphia': 172, 'phnom penh': 173, 'phuentsholing': 174, 'phuket': 175, 'pisa': 176, 'poland': 177, 'port dickson': 178, 'port douglas': 179, 'portugal': 180, 'prague': 181, 'praslin': 182, 'punakha': 183, 'pushkar': 184, 'queenstown': 185, 'ranikhet': 186, 'ranthambore': 187, 'reunion island': 188, 'reykjavik': 189, 'rishikesh': 190, 'rome': 191, 'rotorua': 192, 'salzburg': 193, 'san francisco': 194, 'santorini': 195, 'scandinavia': 196, 'scotland': 197, 'seville': 198, 'seychelles': 199, 'sharjah': 200, 'siem reap': 201, 'singapore': 202, 'sonmarg': 203, 'south africa': 204, 'south goa': 205, 'spain': 206, 'sri lanka': 207, 'sri lanka winter  Packages': 208, 'srinagar': 209, 'st. moritz': 210, 'stockholm': 211, 'stuttgart': 212, 'switzerland': 213, 'sydney': 214, 'tamil nadu': 215, 'tanzania': 216, 'thailand': 217, 'thimphu': 218, 'thiruvananthapuram': 219, 'tiruchirappalli': 220, 'tirupati': 221, 'toronto': 222, 'turkey': 223, 'united arab emirates': 224, 'united kingdom': 225, 'valencia': 226, 'venice': 227, 'vienna': 228, 'vietnam': 229, 'vitoria': 230, 'warsaw': 231, 'washington': 232, 'wellington': 233, 'zagreb': 234, 'zurich': 235}

In [31]:
x=new_df.drop(['price'],axis='columns')
y=new_df['price']

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [33]:
model=KNeighborsRegressor(n_neighbors=5)
model.fit(x_train,y_train)

KNeighborsRegressor()

In [34]:
y_predicted= model.predict(x_test)

In [35]:
x_test

      place  time
1248    206    15
1598     59    12
333     194     1
990      54    12
630     206    17
...     ...   ...
1182     54    12
1533    202    13
1263     11    12
253      59    15
395     129    11

[322 rows x 2 columns]

In [36]:
x_train

      place  time
498      38    12
265     102    11
142      64    12
399     213    16
1080    107    11
...     ...   ...
777      86    12
105     166    11
903     229    11
656      95    14
268     145    11

[1287 rows x 2 columns]

In [37]:
a=float(input("""select the place---
CHOOSE YOUR OPTIONS---

'aberdare': 0,
'abu dhabi': 1,
'agra': 2,
'alibag': 3,
'amman': 4,
'amritsar': 5,
'amsterdam': 6,
'andaman and nicobar islands': 7,
'andhra pradesh': 8,
'athens': 9,
'auckland': 10,
'australia': 11,
'austria': 12

Your choice : """))
b=float(input("""Select the time---
CHOOSE YOUR OPTIONS---

{ 1 NIGHT: 0,
10 NIGHTS: 1,
11 NIGHTS: 2,
12 NIGHTS: 3,
13 NIGHTS: 4,
14 NIGHTS: 5,
15 NIGHTS: 6,
16 NIGHTS: 7,
17 NIGHTS: 8,
19 NIGHTS: 9,
2 NIGHTS: 10,
3 NIGHTS: 11,
4 NIGHTS: 12,
5 NIGHTS: 13,
6 NIGHTS: 14,
7 NIGHTS: 15,
8 NIGHTS: 16,
9 NIGHTS: 17}

Your choice : """))
df=pd.DataFrame([[a],[b]],dtype=int)
y_predicted=model.predict([[a,b]])
print("price is  :",y_predicted)

select the place---
CHOOSE YOUR OPTIONS---

'aberdare': 0,
'abu dhabi': 1,
'agra': 2,
'alibag': 3,
'amman': 4,
'amritsar': 5,
'amsterdam': 6,
'andaman and nicobar islands': 7,
'andhra pradesh': 8,
'athens': 9,
'auckland': 10,
'australia': 11,
'austria': 12

Your choice : 5
Select the time---
CHOOSE YOUR OPTIONS---

{ 1 NIGHT: 0,
10 NIGHTS: 1,
11 NIGHTS: 2,
12 NIGHTS: 3,
13 NIGHTS: 4,
14 NIGHTS: 5,
15 NIGHTS: 6,
16 NIGHTS: 7,
17 NIGHTS: 8,
19 NIGHTS: 9,
2 NIGHTS: 10,
3 NIGHTS: 11,
4 NIGHTS: 12,
5 NIGHTS: 13,
6 NIGHTS: 14,
7 NIGHTS: 15,
8 NIGHTS: 16,
9 NIGHTS: 17}

Your choice : 6
price is  : [13439.]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(